import config from "../config.js";
import productController from "../controller.js";
import createProduct from "../model.js";

export default {
  Query: {
    // Todo: move this to a mutation for JWT
    isAdmin(_, { pass }) {
      if (pass === config.adminPassword) {
        return "fakeJWT";
      }
    },
    product(_, { _id }) {
      return productController.show(_id);
    },
    products() {
      return productController.index();
    },
  },
  Mutation: {
    // Destructure args into product object
    async createProduct(_, { product }) {
      // Incoming product has no id
      const validatedProduct = createProduct(product);
      // id is generated by MongoDB
      const { insertedId: _id } = await productController.create(
        validatedProduct
      );
      return { ...validatedProduct, _id };
    },
    async updateProduct(_, { product }) {
      const validatedProduct = createProduct(product);
      await productController.update(validatedProduct);
      return validatedProduct;
    },
    deleteProduct(_, { _id }) {
      return productController.delete(_id);
    },
  },
};
